apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: crossplane-cluster-test
spec:
  forProvider:
    region: af-south-1
    engineMode: provisioned
    engine: aurora-postgresql
    masterUsername: postgres
    masterUserPasswordSecretRef:
      name: crossplane-cluster-secret-test
      namespace: dev
      key: masterpass
    dbSubnetGroupName: cellcdigital-subnet-group
    vpcSecurityGroupIDs:
      - sg-015474215f201fbdf
    skipFinalSnapshot: true
  writeConnectionSecretToRef:
    name: crossplane-cluster-test-connection-secrets
    namespace: dev