apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: crossplane-rdsinstance-test
spec:
  forProvider:
    engine: aurora
    region: af-south-1
    dbClusterIdentifier: crossplane-cluster-test
    dbInstanceClass: db.t2.small
    masterPasswordSecretRef:
      name: crossplane-test-secret-nil
      namespace: dev
      key: password
  reclaimPolicy: Delete